name: sba2_starter
description: Dart powered Angular2 frontend with Sass and Bootstrap4, Spring Boot backend
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.18
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  ng_bootstrap: any
  sass: any
transformers:
  - angular2:
      platform_directives:
        - 'package:angular2/common.dart#COMMON_DIRECTIVES'
      platform_pipes:
        - 'package:angular2/common.dart#COMMON_PIPES'
      entry_points: web/main.dart
  - sass
  - dart_to_js_script_rewriter